#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("inData_TDATA", 8, hls_in, 0, "axis", "in_data", 1),
	Port_Property("inData_TVALID", 1, hls_in, 1, "axis", "in_vld", 1),
	Port_Property("inData_TREADY", 1, hls_out, 1, "axis", "in_acc", 1),
	Port_Property("inData_TUSER", 128, hls_in, 1, "axis", "in_data", 1),
	Port_Property("outData_TDATA", 8, hls_in, 2, "axis", "in_data", 1),
	Port_Property("outData_TVALID", 1, hls_in, 3, "axis", "in_vld", 1),
	Port_Property("outData_TREADY", 1, hls_out, 3, "axis", "in_acc", 1),
	Port_Property("outData_TUSER", 128, hls_in, 3, "axis", "in_data", 1),
	Port_Property("sfd_detected", 1, hls_out, 4, "ap_vld", "out_data", 1),
	Port_Property("sfd_detected_ap_vld", 1, hls_out, 4, "ap_vld", "out_vld", 1),
	Port_Property("src_addr", 1, hls_out, 5, "ap_vld", "out_data", 1),
	Port_Property("src_addr_ap_vld", 1, hls_out, 5, "ap_vld", "out_vld", 1),
	Port_Property("dest_addr", 1, hls_out, 6, "ap_vld", "out_data", 1),
	Port_Property("dest_addr_ap_vld", 1, hls_out, 6, "ap_vld", "out_vld", 1),
	Port_Property("ethertype", 1, hls_out, 7, "ap_vld", "out_data", 1),
	Port_Property("ethertype_ap_vld", 1, hls_out, 7, "ap_vld", "out_vld", 1),
	Port_Property("ping", 1, hls_out, 8, "ap_vld", "out_data", 1),
	Port_Property("ping_ap_vld", 1, hls_out, 8, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "frameSIPO";
