# 
# Synthesis run script generated by Vivado
# 

set_param project.defaultXPMLibraries XPM_MEMORY
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/brett/workspace/Vivado_WS/pie_hls/solution1/impl/vhdl/project.cache/wt [current_project]
set_property parent.project_path /home/brett/workspace/Vivado_WS/pie_hls/solution1/impl/vhdl/project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib /home/brett/workspace/Vivado_WS/pie_hls/solution1/impl/vhdl/frameSIPO.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/brett/workspace/Vivado_WS/pie_hls/solution1/impl/vhdl/frameSIPO.xdc
set_property used_in_implementation false [get_files /home/brett/workspace/Vivado_WS/pie_hls/solution1/impl/vhdl/frameSIPO.xdc]


synth_design -top frameSIPO -part xc7z020clg484-1 -no_iobuf -mode out_of_context


write_checkpoint -force -noxdef frameSIPO.dcp

catch { report_utilization -file frameSIPO_utilization_synth.rpt -pb frameSIPO_utilization_synth.pb }
