// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _frameSIPO_HH_
#define _frameSIPO_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct frameSIPO : public sc_module {
    // Port declarations 14
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<8> > inData_TDATA;
    sc_in< sc_logic > inData_TVALID;
    sc_out< sc_logic > inData_TREADY;
    sc_in< sc_lv<2> > inData_TUSER;
    sc_out< sc_lv<8> > header;
    sc_out< sc_logic > header_ap_vld;
    sc_out< sc_lv<1> > livewire;
    sc_out< sc_logic > livewire_ap_vld;


    // Module declarations
    frameSIPO(sc_module_name name);
    SC_HAS_PROCESS(frameSIPO);

    ~frameSIPO();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_18;
    sc_signal< sc_lv<1> > p_ZGVZ9frameSIPORN3hls6streamI7;
    sc_signal< sc_lv<16> > packet_length_V;
    sc_signal< sc_lv<1> > CNT_STATE;
    sc_signal< sc_lv<32> > byte_cnt;
    sc_signal< sc_logic > inData_TDATA_blk_n;
    sc_signal< sc_lv<1> > tmp_nbreadreq_fu_94_p4;
    sc_signal< sc_lv<1> > packet_length_V_flag_phi_fu_138_p4;
    sc_signal< bool > ap_sig_50;
    sc_signal< sc_lv<1> > p_ZGVZ9frameSIPORN3hls6streamI7_load_fu_270_p1;
    sc_signal< sc_lv<16> > p_Val2_s_phi_fu_149_p4;
    sc_signal< sc_lv<1> > storemerge_phi_fu_159_p4;
    sc_signal< sc_lv<1> > CNT_STATE_load_load_fu_285_p1;
    sc_signal< sc_lv<1> > tmp_4_fu_297_p2;
    sc_signal< sc_lv<1> > packet_length_V_flag_1_phi_fu_170_p6;
    sc_signal< sc_lv<1> > tmp_7_fu_327_p2;
    sc_signal< sc_lv<1> > tmp_8_fu_333_p2;
    sc_signal< sc_lv<1> > tmp_9_fu_339_p2;
    sc_signal< sc_lv<1> > tmp_s_fu_345_p2;
    sc_signal< sc_lv<1> > tmp_3_fu_351_p2;
    sc_signal< sc_lv<1> > tmp_5_fu_357_p2;
    sc_signal< sc_lv<1> > tmp_2_fu_363_p2;
    sc_signal< sc_lv<16> > p_Result_s_fu_408_p5;
    sc_signal< sc_lv<16> > packet_length_V_new_1_phi_fu_184_p6;
    sc_signal< sc_lv<16> > p_Result_1_fu_395_p5;
    sc_signal< sc_lv<1> > storemerge2_phi_fu_196_p6;
    sc_signal< sc_lv<1> > icmp_fu_379_p2;
    sc_signal< sc_lv<1> > packet_length_V_flag_8_phi_fu_209_p16;
    sc_signal< sc_lv<16> > packet_length_V_new_8_phi_fu_238_p16;
    sc_signal< sc_lv<32> > tmp_6_fu_315_p2;
    sc_signal< sc_lv<8> > storemerge1_cast_cast_fu_386_p3;
    sc_signal< sc_lv<26> > tmp_1_fu_369_p4;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    sc_signal< bool > ap_sig_282;
    sc_signal< bool > ap_sig_181;
    sc_signal< bool > ap_sig_290;
    sc_signal< bool > ap_sig_292;
    sc_signal< bool > ap_sig_161;
    sc_signal< bool > ap_sig_128;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_st1_fsm_0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<8> ap_const_lv8_80;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<8> ap_const_lv8_4;
    static const sc_lv<8> ap_const_lv8_8;
    static const sc_lv<8> ap_const_lv8_10;
    static const sc_lv<8> ap_const_lv8_20;
    static const sc_lv<8> ap_const_lv8_40;
    static const sc_lv<8> ap_const_lv8_D5;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<26> ap_const_lv26_1;
    static const sc_lv<8> ap_const_lv8_2;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_F;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_CNT_STATE_load_load_fu_285_p1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_ap_sig_128();
    void thread_ap_sig_161();
    void thread_ap_sig_18();
    void thread_ap_sig_181();
    void thread_ap_sig_282();
    void thread_ap_sig_290();
    void thread_ap_sig_292();
    void thread_ap_sig_50();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_header();
    void thread_header_ap_vld();
    void thread_icmp_fu_379_p2();
    void thread_inData_TDATA_blk_n();
    void thread_inData_TREADY();
    void thread_livewire();
    void thread_livewire_ap_vld();
    void thread_p_Result_1_fu_395_p5();
    void thread_p_Result_s_fu_408_p5();
    void thread_p_Val2_s_phi_fu_149_p4();
    void thread_p_ZGVZ9frameSIPORN3hls6streamI7_load_fu_270_p1();
    void thread_packet_length_V_flag_1_phi_fu_170_p6();
    void thread_packet_length_V_flag_8_phi_fu_209_p16();
    void thread_packet_length_V_flag_phi_fu_138_p4();
    void thread_packet_length_V_new_1_phi_fu_184_p6();
    void thread_packet_length_V_new_8_phi_fu_238_p16();
    void thread_storemerge1_cast_cast_fu_386_p3();
    void thread_storemerge2_phi_fu_196_p6();
    void thread_storemerge_phi_fu_159_p4();
    void thread_tmp_1_fu_369_p4();
    void thread_tmp_2_fu_363_p2();
    void thread_tmp_3_fu_351_p2();
    void thread_tmp_4_fu_297_p2();
    void thread_tmp_5_fu_357_p2();
    void thread_tmp_6_fu_315_p2();
    void thread_tmp_7_fu_327_p2();
    void thread_tmp_8_fu_333_p2();
    void thread_tmp_9_fu_339_p2();
    void thread_tmp_nbreadreq_fu_94_p4();
    void thread_tmp_s_fu_345_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
