// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "frameSIPO.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic frameSIPO::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic frameSIPO::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> frameSIPO::ap_ST_st1_fsm_0 = "1";
const sc_lv<32> frameSIPO::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> frameSIPO::ap_const_lv1_1 = "1";
const sc_lv<1> frameSIPO::ap_const_lv1_0 = "0";
const sc_lv<16> frameSIPO::ap_const_lv16_0 = "0000000000000000";
const sc_lv<8> frameSIPO::ap_const_lv8_D5 = "11010101";
const sc_lv<32> frameSIPO::ap_const_lv32_1 = "1";
const sc_lv<32> frameSIPO::ap_const_lv32_7 = "111";
const sc_lv<32> frameSIPO::ap_const_lv32_D = "1101";
const sc_lv<32> frameSIPO::ap_const_lv32_E = "1110";
const sc_lv<8> frameSIPO::ap_const_lv8_0 = "00000000";
const sc_lv<16> frameSIPO::ap_const_lv16_800 = "100000000000";

frameSIPO::frameSIPO(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_CNT_STATE_load_load_fu_196_p1);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( CNT_STATE );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_57 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_57 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_127);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );
    sensitive << ( ap_sig_57 );

    SC_METHOD(thread_ap_sig_18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_192);
    sensitive << ( CNT_STATE_load_load_fu_196_p1 );
    sensitive << ( tmp_6_fu_239_p2 );
    sensitive << ( tmp_7_fu_245_p2 );
    sensitive << ( tmp_8_fu_251_p2 );
    sensitive << ( tmp_2_fu_257_p2 );

    SC_METHOD(thread_ap_sig_51);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );

    SC_METHOD(thread_ap_sig_57);
    sensitive << ( ap_start );
    sensitive << ( inData_TVALID );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_18 );

    SC_METHOD(thread_dest_addr);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );
    sensitive << ( ap_sig_57 );
    sensitive << ( CNT_STATE_load_load_fu_196_p1 );
    sensitive << ( tmp_6_fu_239_p2 );
    sensitive << ( tmp_7_fu_245_p2 );
    sensitive << ( tmp_8_fu_251_p2 );
    sensitive << ( tmp_2_fu_257_p2 );

    SC_METHOD(thread_dest_addr_ap_vld);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );
    sensitive << ( ap_sig_57 );
    sensitive << ( CNT_STATE_load_load_fu_196_p1 );
    sensitive << ( tmp_6_fu_239_p2 );
    sensitive << ( tmp_7_fu_245_p2 );
    sensitive << ( tmp_8_fu_251_p2 );
    sensitive << ( tmp_2_fu_257_p2 );

    SC_METHOD(thread_ethertype);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );
    sensitive << ( ap_sig_57 );
    sensitive << ( CNT_STATE_load_load_fu_196_p1 );
    sensitive << ( tmp_6_fu_239_p2 );
    sensitive << ( tmp_7_fu_245_p2 );
    sensitive << ( tmp_8_fu_251_p2 );
    sensitive << ( tmp_2_fu_257_p2 );

    SC_METHOD(thread_ethertype_ap_vld);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );
    sensitive << ( ap_sig_57 );
    sensitive << ( CNT_STATE_load_load_fu_196_p1 );
    sensitive << ( tmp_6_fu_239_p2 );
    sensitive << ( tmp_7_fu_245_p2 );
    sensitive << ( tmp_8_fu_251_p2 );
    sensitive << ( tmp_2_fu_257_p2 );

    SC_METHOD(thread_inData_TDATA_blk_n);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( inData_TVALID );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );

    SC_METHOD(thread_inData_TREADY);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );
    sensitive << ( ap_sig_57 );

    SC_METHOD(thread_outData_TREADY);

    SC_METHOD(thread_packet_type_load_1_phi_fu_178_p12);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );
    sensitive << ( CNT_STATE_load_load_fu_196_p1 );
    sensitive << ( tmp_6_fu_239_p2 );
    sensitive << ( tmp_7_fu_245_p2 );
    sensitive << ( tmp_8_fu_251_p2 );
    sensitive << ( tmp_2_fu_257_p2 );
    sensitive << ( tmp_s_fu_274_p3 );
    sensitive << ( tmp_4_fu_269_p1 );

    SC_METHOD(thread_ping);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );
    sensitive << ( ap_sig_57 );
    sensitive << ( packet_type_load_1_phi_fu_178_p12 );

    SC_METHOD(thread_ping_ap_vld);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );
    sensitive << ( ap_sig_57 );

    SC_METHOD(thread_sfd_detected);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );
    sensitive << ( sfd_detected_flag_1_phi_fu_132_p12 );
    sensitive << ( ap_sig_57 );
    sensitive << ( sfd_detected_new_1_phi_fu_155_p12 );

    SC_METHOD(thread_sfd_detected_ap_vld);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );
    sensitive << ( sfd_detected_flag_1_phi_fu_132_p12 );
    sensitive << ( ap_sig_57 );

    SC_METHOD(thread_sfd_detected_flag_1_phi_fu_132_p12);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );
    sensitive << ( CNT_STATE_load_load_fu_196_p1 );
    sensitive << ( tmp_6_fu_239_p2 );
    sensitive << ( tmp_7_fu_245_p2 );
    sensitive << ( tmp_8_fu_251_p2 );
    sensitive << ( tmp_2_fu_257_p2 );

    SC_METHOD(thread_sfd_detected_new_1_phi_fu_155_p12);
    sensitive << ( CNT_STATE_load_load_fu_196_p1 );
    sensitive << ( tmp_3_fu_214_p2 );
    sensitive << ( ap_sig_192 );
    sensitive << ( ap_sig_51 );

    SC_METHOD(thread_src_addr);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );
    sensitive << ( ap_sig_57 );
    sensitive << ( CNT_STATE_load_load_fu_196_p1 );
    sensitive << ( tmp_6_fu_239_p2 );
    sensitive << ( tmp_7_fu_245_p2 );
    sensitive << ( tmp_8_fu_251_p2 );
    sensitive << ( tmp_2_fu_257_p2 );

    SC_METHOD(thread_src_addr_ap_vld);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );
    sensitive << ( ap_sig_57 );
    sensitive << ( CNT_STATE_load_load_fu_196_p1 );
    sensitive << ( tmp_6_fu_239_p2 );
    sensitive << ( tmp_7_fu_245_p2 );
    sensitive << ( tmp_8_fu_251_p2 );
    sensitive << ( tmp_2_fu_257_p2 );

    SC_METHOD(thread_tmp_2_fu_257_p2);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );
    sensitive << ( ap_sig_57 );
    sensitive << ( CNT_STATE_load_load_fu_196_p1 );
    sensitive << ( tmp_6_fu_239_p2 );
    sensitive << ( tmp_7_fu_245_p2 );
    sensitive << ( tmp_8_fu_251_p2 );
    sensitive << ( tmp_5_fu_227_p2 );

    SC_METHOD(thread_tmp_3_fu_214_p2);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( inData_TDATA );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );
    sensitive << ( ap_sig_57 );
    sensitive << ( CNT_STATE_load_load_fu_196_p1 );

    SC_METHOD(thread_tmp_4_fu_269_p1);
    sensitive << ( inData_TDATA );

    SC_METHOD(thread_tmp_5_fu_227_p2);
    sensitive << ( byte_cnt );

    SC_METHOD(thread_tmp_6_fu_239_p2);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );
    sensitive << ( ap_sig_57 );
    sensitive << ( CNT_STATE_load_load_fu_196_p1 );
    sensitive << ( tmp_5_fu_227_p2 );

    SC_METHOD(thread_tmp_7_fu_245_p2);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );
    sensitive << ( ap_sig_57 );
    sensitive << ( CNT_STATE_load_load_fu_196_p1 );
    sensitive << ( tmp_6_fu_239_p2 );
    sensitive << ( tmp_5_fu_227_p2 );

    SC_METHOD(thread_tmp_8_fu_251_p2);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_nbreadreq_fu_70_p4 );
    sensitive << ( ap_sig_57 );
    sensitive << ( CNT_STATE_load_load_fu_196_p1 );
    sensitive << ( tmp_6_fu_239_p2 );
    sensitive << ( tmp_7_fu_245_p2 );
    sensitive << ( tmp_5_fu_227_p2 );

    SC_METHOD(thread_tmp_nbreadreq_fu_70_p4);
    sensitive << ( inData_TVALID );

    SC_METHOD(thread_tmp_s_fu_274_p3);
    sensitive << ( inData_TDATA );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_57 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "1";
    CNT_STATE = "0";
    byte_cnt = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "frameSIPO_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, inData_TDATA, "(port)inData_TDATA");
    sc_trace(mVcdFile, inData_TVALID, "(port)inData_TVALID");
    sc_trace(mVcdFile, inData_TREADY, "(port)inData_TREADY");
    sc_trace(mVcdFile, inData_TUSER, "(port)inData_TUSER");
    sc_trace(mVcdFile, outData_TDATA, "(port)outData_TDATA");
    sc_trace(mVcdFile, outData_TVALID, "(port)outData_TVALID");
    sc_trace(mVcdFile, outData_TREADY, "(port)outData_TREADY");
    sc_trace(mVcdFile, outData_TUSER, "(port)outData_TUSER");
    sc_trace(mVcdFile, sfd_detected, "(port)sfd_detected");
    sc_trace(mVcdFile, sfd_detected_ap_vld, "(port)sfd_detected_ap_vld");
    sc_trace(mVcdFile, src_addr, "(port)src_addr");
    sc_trace(mVcdFile, src_addr_ap_vld, "(port)src_addr_ap_vld");
    sc_trace(mVcdFile, dest_addr, "(port)dest_addr");
    sc_trace(mVcdFile, dest_addr_ap_vld, "(port)dest_addr_ap_vld");
    sc_trace(mVcdFile, ethertype, "(port)ethertype");
    sc_trace(mVcdFile, ethertype_ap_vld, "(port)ethertype_ap_vld");
    sc_trace(mVcdFile, ping, "(port)ping");
    sc_trace(mVcdFile, ping_ap_vld, "(port)ping_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_18, "ap_sig_18");
    sc_trace(mVcdFile, CNT_STATE, "CNT_STATE");
    sc_trace(mVcdFile, byte_cnt, "byte_cnt");
    sc_trace(mVcdFile, inData_TDATA_blk_n, "inData_TDATA_blk_n");
    sc_trace(mVcdFile, tmp_nbreadreq_fu_70_p4, "tmp_nbreadreq_fu_70_p4");
    sc_trace(mVcdFile, sfd_detected_flag_1_phi_fu_132_p12, "sfd_detected_flag_1_phi_fu_132_p12");
    sc_trace(mVcdFile, ap_sig_57, "ap_sig_57");
    sc_trace(mVcdFile, CNT_STATE_load_load_fu_196_p1, "CNT_STATE_load_load_fu_196_p1");
    sc_trace(mVcdFile, tmp_6_fu_239_p2, "tmp_6_fu_239_p2");
    sc_trace(mVcdFile, tmp_7_fu_245_p2, "tmp_7_fu_245_p2");
    sc_trace(mVcdFile, tmp_8_fu_251_p2, "tmp_8_fu_251_p2");
    sc_trace(mVcdFile, tmp_2_fu_257_p2, "tmp_2_fu_257_p2");
    sc_trace(mVcdFile, sfd_detected_new_1_phi_fu_155_p12, "sfd_detected_new_1_phi_fu_155_p12");
    sc_trace(mVcdFile, tmp_3_fu_214_p2, "tmp_3_fu_214_p2");
    sc_trace(mVcdFile, packet_type_load_1_phi_fu_178_p12, "packet_type_load_1_phi_fu_178_p12");
    sc_trace(mVcdFile, tmp_s_fu_274_p3, "tmp_s_fu_274_p3");
    sc_trace(mVcdFile, tmp_4_fu_269_p1, "tmp_4_fu_269_p1");
    sc_trace(mVcdFile, tmp_5_fu_227_p2, "tmp_5_fu_227_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_192, "ap_sig_192");
    sc_trace(mVcdFile, ap_sig_127, "ap_sig_127");
    sc_trace(mVcdFile, ap_sig_51, "ap_sig_51");
#endif

    }
    mHdltvinHandle.open("frameSIPO.hdltvin.dat");
    mHdltvoutHandle.open("frameSIPO.hdltvout.dat");
}

frameSIPO::~frameSIPO() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void frameSIPO::thread_ap_clk_no_reset_() {
    if (ap_sig_127.read()) {
        if (ap_sig_192.read()) {
            CNT_STATE = ap_const_lv1_0;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read())) {
            CNT_STATE = tmp_3_fu_214_p2.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (ap_sig_127.read()) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read())) {
            byte_cnt = tmp_5_fu_227_p2.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read())) {
            byte_cnt = ap_const_lv32_0;
        }
    }
}

void frameSIPO::thread_CNT_STATE_load_load_fu_196_p1() {
    CNT_STATE_load_load_fu_196_p1 = CNT_STATE.read();
}

void frameSIPO::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_57.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void frameSIPO::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void frameSIPO::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_57.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void frameSIPO::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void frameSIPO::thread_ap_sig_127() {
    ap_sig_127 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && !ap_sig_57.read());
}

void frameSIPO::thread_ap_sig_18() {
    ap_sig_18 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void frameSIPO::thread_ap_sig_192() {
    ap_sig_192 = (!esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_251_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_257_p2.read()));
}

void frameSIPO::thread_ap_sig_51() {
    ap_sig_51 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()));
}

void frameSIPO::thread_ap_sig_57() {
    ap_sig_57 = ((!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
  esl_seteq<1,1,1>(inData_TVALID.read(), ap_const_logic_0)) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0));
}

void frameSIPO::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_18.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void frameSIPO::thread_dest_addr() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
         !ap_sig_57.read() && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()))) {
        dest_addr = ap_const_lv1_1;
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
                 !ap_sig_57.read() && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_251_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_257_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
                 !ap_sig_57.read() && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read())))) {
        dest_addr = ap_const_lv1_0;
    } else {
        dest_addr = "X";
    }
}

void frameSIPO::thread_dest_addr_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
          !ap_sig_57.read() && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
          !ap_sig_57.read() && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_251_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_257_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
          !ap_sig_57.read() && 
          esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read())))) {
        dest_addr_ap_vld = ap_const_logic_1;
    } else {
        dest_addr_ap_vld = ap_const_logic_0;
    }
}

void frameSIPO::thread_ethertype() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
          !ap_sig_57.read() && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_251_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
          !ap_sig_57.read() && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_251_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_257_p2.read())))) {
        ethertype = ap_const_lv1_1;
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
                 !ap_sig_57.read() && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_251_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_257_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
                 !ap_sig_57.read() && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read())))) {
        ethertype = ap_const_lv1_0;
    } else {
        ethertype = "X";
    }
}

void frameSIPO::thread_ethertype_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
          !ap_sig_57.read() && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_251_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
          !ap_sig_57.read() && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_251_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_257_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
          !ap_sig_57.read() && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_251_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_257_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
          !ap_sig_57.read() && 
          esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read())))) {
        ethertype_ap_vld = ap_const_logic_1;
    } else {
        ethertype_ap_vld = ap_const_logic_0;
    }
}

void frameSIPO::thread_inData_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()))) {
        inData_TDATA_blk_n = inData_TVALID.read();
    } else {
        inData_TDATA_blk_n = ap_const_logic_1;
    }
}

void frameSIPO::thread_inData_TREADY() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
          !ap_sig_57.read()))) {
        inData_TREADY = ap_const_logic_1;
    } else {
        inData_TREADY = ap_const_logic_0;
    }
}

void frameSIPO::thread_outData_TREADY() {
    outData_TREADY = ap_const_logic_0;
}

void frameSIPO::thread_packet_type_load_1_phi_fu_178_p12() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_251_p2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_257_p2.read()))) {
        packet_type_load_1_phi_fu_178_p12 = tmp_4_fu_269_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_251_p2.read()))) {
        packet_type_load_1_phi_fu_178_p12 = tmp_s_fu_274_p3.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_251_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_257_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read())))) {
        packet_type_load_1_phi_fu_178_p12 = ap_const_lv16_0;
    } else {
        packet_type_load_1_phi_fu_178_p12 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void frameSIPO::thread_ping() {
    ping = (!packet_type_load_1_phi_fu_178_p12.read().is_01() || !ap_const_lv16_800.is_01())? sc_lv<1>(): sc_lv<1>(packet_type_load_1_phi_fu_178_p12.read() == ap_const_lv16_800);
}

void frameSIPO::thread_ping_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
         !ap_sig_57.read())) {
        ping_ap_vld = ap_const_logic_1;
    } else {
        ping_ap_vld = ap_const_logic_0;
    }
}

void frameSIPO::thread_sfd_detected() {
    sfd_detected = sfd_detected_new_1_phi_fu_155_p12.read();
}

void frameSIPO::thread_sfd_detected_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
         !ap_sig_57.read() && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, sfd_detected_flag_1_phi_fu_132_p12.read()))) {
        sfd_detected_ap_vld = ap_const_logic_1;
    } else {
        sfd_detected_ap_vld = ap_const_logic_0;
    }
}

void frameSIPO::thread_sfd_detected_flag_1_phi_fu_132_p12() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_251_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_257_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read())))) {
        sfd_detected_flag_1_phi_fu_132_p12 = ap_const_lv1_1;
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_251_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_251_p2.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_257_p2.read())))) {
        sfd_detected_flag_1_phi_fu_132_p12 = ap_const_lv1_0;
    } else {
        sfd_detected_flag_1_phi_fu_132_p12 = "X";
    }
}

void frameSIPO::thread_sfd_detected_new_1_phi_fu_155_p12() {
    if (ap_sig_51.read()) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read())) {
            sfd_detected_new_1_phi_fu_155_p12 = tmp_3_fu_214_p2.read();
        } else if (ap_sig_192.read()) {
            sfd_detected_new_1_phi_fu_155_p12 = ap_const_lv1_0;
        } else {
            sfd_detected_new_1_phi_fu_155_p12 = "X";
        }
    } else {
        sfd_detected_new_1_phi_fu_155_p12 = "X";
    }
}

void frameSIPO::thread_src_addr() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
         !ap_sig_57.read() && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read()))) {
        src_addr = ap_const_lv1_1;
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
                 !ap_sig_57.read() && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_251_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_257_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
                 !ap_sig_57.read() && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read())))) {
        src_addr = ap_const_lv1_0;
    } else {
        src_addr = "X";
    }
}

void frameSIPO::thread_src_addr_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
          !ap_sig_57.read() && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
          !ap_sig_57.read() && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_239_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_245_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_251_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_257_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_70_p4.read()) && 
          !ap_sig_57.read() && 
          esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_196_p1.read())))) {
        src_addr_ap_vld = ap_const_logic_1;
    } else {
        src_addr_ap_vld = ap_const_logic_0;
    }
}

void frameSIPO::thread_tmp_2_fu_257_p2() {
    tmp_2_fu_257_p2 = (!tmp_5_fu_227_p2.read().is_01() || !ap_const_lv32_E.is_01())? sc_lv<1>(): sc_lv<1>(tmp_5_fu_227_p2.read() == ap_const_lv32_E);
}

void frameSIPO::thread_tmp_3_fu_214_p2() {
    tmp_3_fu_214_p2 = (!inData_TDATA.read().is_01() || !ap_const_lv8_D5.is_01())? sc_lv<1>(): sc_lv<1>(inData_TDATA.read() == ap_const_lv8_D5);
}

void frameSIPO::thread_tmp_4_fu_269_p1() {
    tmp_4_fu_269_p1 = esl_zext<16,8>(inData_TDATA.read());
}

void frameSIPO::thread_tmp_5_fu_227_p2() {
    tmp_5_fu_227_p2 = (!byte_cnt.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(byte_cnt.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void frameSIPO::thread_tmp_6_fu_239_p2() {
    tmp_6_fu_239_p2 = (!tmp_5_fu_227_p2.read().is_01() || !ap_const_lv32_7.is_01())? sc_lv<1>(): (sc_bigint<32>(tmp_5_fu_227_p2.read()) < sc_bigint<32>(ap_const_lv32_7));
}

void frameSIPO::thread_tmp_7_fu_245_p2() {
    tmp_7_fu_245_p2 = (!tmp_5_fu_227_p2.read().is_01() || !ap_const_lv32_D.is_01())? sc_lv<1>(): (sc_bigint<32>(tmp_5_fu_227_p2.read()) < sc_bigint<32>(ap_const_lv32_D));
}

void frameSIPO::thread_tmp_8_fu_251_p2() {
    tmp_8_fu_251_p2 = (!tmp_5_fu_227_p2.read().is_01() || !ap_const_lv32_D.is_01())? sc_lv<1>(): sc_lv<1>(tmp_5_fu_227_p2.read() == ap_const_lv32_D);
}

void frameSIPO::thread_tmp_nbreadreq_fu_70_p4() {
    tmp_nbreadreq_fu_70_p4 =  (sc_lv<1>) ((inData_TVALID.read()));
}

void frameSIPO::thread_tmp_s_fu_274_p3() {
    tmp_s_fu_274_p3 = esl_concat<8,8>(inData_TDATA.read(), ap_const_lv8_0);
}

void frameSIPO::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

void frameSIPO::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inData_TDATA\" :  \"" << inData_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inData_TVALID\" :  \"" << inData_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"inData_TREADY\" :  \"" << inData_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inData_TUSER\" :  \"" << inData_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"outData_TDATA\" :  \"" << outData_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"outData_TVALID\" :  \"" << outData_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outData_TREADY\" :  \"" << outData_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"outData_TUSER\" :  \"" << outData_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sfd_detected\" :  \"" << sfd_detected.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sfd_detected_ap_vld\" :  \"" << sfd_detected_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"src_addr\" :  \"" << src_addr.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"src_addr_ap_vld\" :  \"" << src_addr_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dest_addr\" :  \"" << dest_addr.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dest_addr_ap_vld\" :  \"" << dest_addr_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ethertype\" :  \"" << ethertype.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ethertype_ap_vld\" :  \"" << ethertype_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ping\" :  \"" << ping.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ping_ap_vld\" :  \"" << ping_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

