// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "frameSIPO.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic frameSIPO::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic frameSIPO::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> frameSIPO::ap_ST_st1_fsm0_0 = "1";
const sc_lv<2> frameSIPO::ap_ST_st2_fsm1_1 = "10";
const sc_lv<2> frameSIPO::ap_ST_st0_fsm1_0 = "1";
const sc_lv<32> frameSIPO::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> frameSIPO::ap_const_lv1_1 = "1";
const sc_lv<1> frameSIPO::ap_const_lv1_0 = "0";
const sc_lv<32> frameSIPO::ap_const_lv32_1 = "1";
const sc_lv<8> frameSIPO::ap_const_lv8_0 = "00000000";
const sc_lv<8> frameSIPO::ap_const_lv8_80 = "10000000";
const sc_lv<8> frameSIPO::ap_const_lv8_20 = "100000";
const sc_lv<8> frameSIPO::ap_const_lv8_8 = "1000";
const sc_lv<8> frameSIPO::ap_const_lv8_4 = "100";
const sc_lv<8> frameSIPO::ap_const_lv8_10 = "10000";
const sc_lv<8> frameSIPO::ap_const_lv8_40 = "1000000";
const sc_lv<8> frameSIPO::ap_const_lv8_D5 = "11010101";
const sc_lv<32> frameSIPO::ap_const_lv32_7 = "111";
const sc_lv<32> frameSIPO::ap_const_lv32_D = "1101";
const sc_lv<32> frameSIPO::ap_const_lv32_E = "1110";
const sc_lv<32> frameSIPO::ap_const_lv32_11 = "10001";
const sc_lv<32> frameSIPO::ap_const_lv32_FFFFFFF0 = "11111111111111111111111111110000";
const sc_lv<32> frameSIPO::ap_const_lv32_1F = "11111";
const sc_lv<31> frameSIPO::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<32> frameSIPO::ap_const_lv32_6 = "110";
const sc_lv<26> frameSIPO::ap_const_lv26_1 = "1";
const sc_lv<3> frameSIPO::ap_const_lv3_7 = "111";
const sc_lv<3> frameSIPO::ap_const_lv3_2 = "10";
const sc_lv<3> frameSIPO::ap_const_lv3_1 = "1";
const bool frameSIPO::ap_true = true;

frameSIPO::frameSIPO(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_CNT_STATE_load_load_fu_183_p1);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm0_0 );
    sensitive << ( tmp_nbreadreq_fu_88_p4 );
    sensitive << ( CNT_STATE );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st2_fsm1_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm0_0 );
    sensitive << ( ap_sig_cseq_ST_st0_fsm1_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st1_fsm0_0 );
    sensitive << ( ap_sig_45 );

    SC_METHOD(thread_ap_reg_phiprechg_header_new_6_reg_146pp0_it0);

    SC_METHOD(thread_ap_reg_phiprechg_header_new_reg_133pp0_it0);

    SC_METHOD(thread_ap_reg_phiprechg_storemerge_reg_122pp0_it0);

    SC_METHOD(thread_ap_reg_ppstg_CNT_STATE_load_reg_328_pp0_iter0);
    sensitive << ( CNT_STATE_load_reg_328 );

    SC_METHOD(thread_ap_reg_ppstg_tmp_6_reg_335_pp0_iter0);
    sensitive << ( tmp_6_reg_335 );

    SC_METHOD(thread_ap_reg_ppstg_tmp_7_reg_339_pp0_iter0);
    sensitive << ( tmp_7_reg_339 );

    SC_METHOD(thread_ap_reg_ppstg_tmp_8_reg_343_pp0_iter0);
    sensitive << ( tmp_8_reg_343 );

    SC_METHOD(thread_ap_reg_ppstg_tmp_9_reg_347_pp0_iter0);
    sensitive << ( tmp_9_reg_347 );

    SC_METHOD(thread_ap_reg_ppstg_tmp_reg_324_pp0_iter0);
    sensitive << ( tmp_reg_324 );

    SC_METHOD(thread_ap_reg_ppstg_tmp_s_reg_351_pp0_iter0);
    sensitive << ( tmp_s_reg_351 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_136);
    sensitive << ( tmp_nbreadreq_fu_88_p4 );
    sensitive << ( CNT_STATE_load_load_fu_183_p1 );
    sensitive << ( tmp_3_fu_195_p2 );

    SC_METHOD(thread_ap_sig_142);
    sensitive << ( tmp_nbreadreq_fu_88_p4 );
    sensitive << ( CNT_STATE_load_load_fu_183_p1 );
    sensitive << ( tmp_3_fu_195_p2 );

    SC_METHOD(thread_ap_sig_160);
    sensitive << ( tmp_nbreadreq_fu_88_p4 );
    sensitive << ( CNT_STATE_load_load_fu_183_p1 );
    sensitive << ( tmp_6_fu_225_p2 );
    sensitive << ( tmp_7_fu_231_p2 );

    SC_METHOD(thread_ap_sig_164);
    sensitive << ( tmp_nbreadreq_fu_88_p4 );
    sensitive << ( CNT_STATE_load_load_fu_183_p1 );
    sensitive << ( tmp_6_fu_225_p2 );
    sensitive << ( tmp_7_fu_231_p2 );
    sensitive << ( tmp_8_fu_237_p2 );
    sensitive << ( tmp_9_fu_243_p2 );

    SC_METHOD(thread_ap_sig_173);
    sensitive << ( tmp_nbreadreq_fu_88_p4 );
    sensitive << ( CNT_STATE_load_load_fu_183_p1 );
    sensitive << ( tmp_6_fu_225_p2 );
    sensitive << ( tmp_7_fu_231_p2 );
    sensitive << ( tmp_8_fu_237_p2 );
    sensitive << ( tmp_9_fu_243_p2 );
    sensitive << ( tmp_s_fu_249_p2 );

    SC_METHOD(thread_ap_sig_191);
    sensitive << ( tmp_nbreadreq_fu_88_p4 );
    sensitive << ( CNT_STATE_load_load_fu_183_p1 );
    sensitive << ( tmp_6_fu_225_p2 );
    sensitive << ( tmp_7_fu_231_p2 );
    sensitive << ( tmp_8_fu_237_p2 );

    SC_METHOD(thread_ap_sig_195);
    sensitive << ( tmp_nbreadreq_fu_88_p4 );
    sensitive << ( CNT_STATE_load_load_fu_183_p1 );
    sensitive << ( tmp_6_fu_225_p2 );

    SC_METHOD(thread_ap_sig_21);
    sensitive << ( ap_CS_fsm0 );

    SC_METHOD(thread_ap_sig_212);
    sensitive << ( ap_sig_cseq_ST_st2_fsm1_1 );
    sensitive << ( ap_reg_ppstg_tmp_reg_324_pp0_iter0 );

    SC_METHOD(thread_ap_sig_315);
    sensitive << ( CNT_STATE_load_load_fu_183_p1 );
    sensitive << ( tmp_3_fu_195_p2 );

    SC_METHOD(thread_ap_sig_32);
    sensitive << ( ap_CS_fsm1 );

    SC_METHOD(thread_ap_sig_322);
    sensitive << ( ap_reg_ppstg_CNT_STATE_load_reg_328_pp0_iter0 );
    sensitive << ( ap_reg_ppstg_tmp_6_reg_335_pp0_iter0 );
    sensitive << ( ap_reg_ppstg_tmp_7_reg_339_pp0_iter0 );
    sensitive << ( ap_reg_ppstg_tmp_8_reg_343_pp0_iter0 );
    sensitive << ( ap_reg_ppstg_tmp_9_reg_347_pp0_iter0 );
    sensitive << ( ap_reg_ppstg_tmp_s_reg_351_pp0_iter0 );

    SC_METHOD(thread_ap_sig_325);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm0_0 );
    sensitive << ( tmp_nbreadreq_fu_88_p4 );
    sensitive << ( CNT_STATE_load_load_fu_183_p1 );

    SC_METHOD(thread_ap_sig_45);
    sensitive << ( ap_start );
    sensitive << ( inData_TVALID );
    sensitive << ( tmp_nbreadreq_fu_88_p4 );

    SC_METHOD(thread_ap_sig_51);
    sensitive << ( ap_CS_fsm1 );

    SC_METHOD(thread_ap_sig_55);
    sensitive << ( ap_sig_cseq_ST_st1_fsm0_0 );
    sensitive << ( ap_sig_45 );

    SC_METHOD(thread_ap_sig_82);
    sensitive << ( ap_sig_cseq_ST_st1_fsm0_0 );
    sensitive << ( tmp_nbreadreq_fu_88_p4 );
    sensitive << ( ap_sig_45 );

    SC_METHOD(thread_ap_sig_cseq_ST_st0_fsm1_0);
    sensitive << ( ap_sig_32 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm0_0);
    sensitive << ( ap_sig_21 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm1_1);
    sensitive << ( ap_sig_51 );

    SC_METHOD(thread_header);
    sensitive << ( ap_sig_cseq_ST_st2_fsm1_1 );
    sensitive << ( ap_reg_ppstg_tmp_reg_324_pp0_iter0 );
    sensitive << ( header_new_6_phi_fu_154_p14 );

    SC_METHOD(thread_header_ap_vld);
    sensitive << ( ap_sig_cseq_ST_st2_fsm1_1 );
    sensitive << ( ap_reg_ppstg_tmp_reg_324_pp0_iter0 );

    SC_METHOD(thread_header_new_6_phi_fu_154_p14);
    sensitive << ( ap_reg_ppstg_CNT_STATE_load_reg_328_pp0_iter0 );
    sensitive << ( ap_reg_phiprechg_header_new_reg_133pp0_it1 );
    sensitive << ( ap_reg_phiprechg_header_new_6_reg_146pp0_it1 );
    sensitive << ( storemerge2_cast_fu_319_p1 );
    sensitive << ( ap_sig_322 );
    sensitive << ( ap_sig_212 );

    SC_METHOD(thread_icmp5_fu_287_p2);
    sensitive << ( ap_sig_cseq_ST_st1_fsm0_0 );
    sensitive << ( tmp_nbreadreq_fu_88_p4 );
    sensitive << ( ap_sig_45 );
    sensitive << ( CNT_STATE_load_load_fu_183_p1 );
    sensitive << ( tmp_6_fu_225_p2 );
    sensitive << ( tmp_7_fu_231_p2 );
    sensitive << ( tmp_8_fu_237_p2 );
    sensitive << ( tmp_9_fu_243_p2 );
    sensitive << ( tmp_s_fu_249_p2 );
    sensitive << ( tmp_4_fu_277_p4 );

    SC_METHOD(thread_icmp_fu_271_p2);
    sensitive << ( ap_sig_cseq_ST_st1_fsm0_0 );
    sensitive << ( tmp_nbreadreq_fu_88_p4 );
    sensitive << ( ap_sig_45 );
    sensitive << ( CNT_STATE_load_load_fu_183_p1 );
    sensitive << ( tmp_6_fu_225_p2 );
    sensitive << ( tmp_7_fu_231_p2 );
    sensitive << ( tmp_8_fu_237_p2 );
    sensitive << ( tmp_9_fu_243_p2 );
    sensitive << ( tmp_s_fu_249_p2 );
    sensitive << ( tmp_2_fu_261_p4 );

    SC_METHOD(thread_inData_TDATA_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm0_0 );
    sensitive << ( inData_TVALID );
    sensitive << ( tmp_nbreadreq_fu_88_p4 );

    SC_METHOD(thread_inData_TREADY);
    sensitive << ( ap_sig_cseq_ST_st1_fsm0_0 );
    sensitive << ( tmp_nbreadreq_fu_88_p4 );
    sensitive << ( ap_sig_45 );

    SC_METHOD(thread_livewire);
    sensitive << ( ap_reg_ppstg_CNT_STATE_load_reg_328_pp0_iter0 );
    sensitive << ( ap_sig_212 );

    SC_METHOD(thread_livewire_ap_vld);
    sensitive << ( ap_sig_cseq_ST_st2_fsm1_1 );
    sensitive << ( ap_reg_ppstg_tmp_reg_324_pp0_iter0 );
    sensitive << ( ap_reg_ppstg_CNT_STATE_load_reg_328_pp0_iter0 );

    SC_METHOD(thread_p_off_fu_255_p2);
    sensitive << ( byte_cnt );

    SC_METHOD(thread_storemerge1_cast_fu_305_p3);
    sensitive << ( icmp_reg_355 );

    SC_METHOD(thread_storemerge2_cast_fu_319_p1);
    sensitive << ( storemerge2_fu_312_p3 );

    SC_METHOD(thread_storemerge2_fu_312_p3);
    sensitive << ( tmp_1_reg_360 );
    sensitive << ( storemerge1_cast_fu_305_p3 );

    SC_METHOD(thread_storemerge_phi_fu_125_p4);
    sensitive << ( ap_reg_phiprechg_storemerge_reg_122pp0_it0 );
    sensitive << ( tmp_3_fu_195_p2 );
    sensitive << ( ap_sig_325 );

    SC_METHOD(thread_tmp_1_fu_293_p2);
    sensitive << ( icmp_fu_271_p2 );
    sensitive << ( icmp5_fu_287_p2 );

    SC_METHOD(thread_tmp_2_fu_261_p4);
    sensitive << ( p_off_fu_255_p2 );

    SC_METHOD(thread_tmp_3_fu_195_p2);
    sensitive << ( ap_sig_cseq_ST_st1_fsm0_0 );
    sensitive << ( tmp_nbreadreq_fu_88_p4 );
    sensitive << ( ap_sig_45 );
    sensitive << ( inData_TDATA );
    sensitive << ( CNT_STATE_load_load_fu_183_p1 );

    SC_METHOD(thread_tmp_4_fu_277_p4);
    sensitive << ( tmp_5_fu_213_p2 );

    SC_METHOD(thread_tmp_5_fu_213_p2);
    sensitive << ( byte_cnt );

    SC_METHOD(thread_tmp_6_fu_225_p2);
    sensitive << ( ap_sig_cseq_ST_st1_fsm0_0 );
    sensitive << ( tmp_nbreadreq_fu_88_p4 );
    sensitive << ( ap_sig_45 );
    sensitive << ( CNT_STATE_load_load_fu_183_p1 );
    sensitive << ( tmp_5_fu_213_p2 );

    SC_METHOD(thread_tmp_7_fu_231_p2);
    sensitive << ( ap_sig_cseq_ST_st1_fsm0_0 );
    sensitive << ( tmp_nbreadreq_fu_88_p4 );
    sensitive << ( ap_sig_45 );
    sensitive << ( CNT_STATE_load_load_fu_183_p1 );
    sensitive << ( tmp_6_fu_225_p2 );
    sensitive << ( tmp_5_fu_213_p2 );

    SC_METHOD(thread_tmp_8_fu_237_p2);
    sensitive << ( ap_sig_cseq_ST_st1_fsm0_0 );
    sensitive << ( tmp_nbreadreq_fu_88_p4 );
    sensitive << ( ap_sig_45 );
    sensitive << ( CNT_STATE_load_load_fu_183_p1 );
    sensitive << ( tmp_6_fu_225_p2 );
    sensitive << ( tmp_7_fu_231_p2 );
    sensitive << ( tmp_5_fu_213_p2 );

    SC_METHOD(thread_tmp_9_fu_243_p2);
    sensitive << ( ap_sig_cseq_ST_st1_fsm0_0 );
    sensitive << ( tmp_nbreadreq_fu_88_p4 );
    sensitive << ( ap_sig_45 );
    sensitive << ( CNT_STATE_load_load_fu_183_p1 );
    sensitive << ( tmp_6_fu_225_p2 );
    sensitive << ( tmp_7_fu_231_p2 );
    sensitive << ( tmp_8_fu_237_p2 );
    sensitive << ( tmp_5_fu_213_p2 );

    SC_METHOD(thread_tmp_nbreadreq_fu_88_p4);
    sensitive << ( inData_TVALID );

    SC_METHOD(thread_tmp_s_fu_249_p2);
    sensitive << ( ap_sig_cseq_ST_st1_fsm0_0 );
    sensitive << ( tmp_nbreadreq_fu_88_p4 );
    sensitive << ( ap_sig_45 );
    sensitive << ( CNT_STATE_load_load_fu_183_p1 );
    sensitive << ( tmp_6_fu_225_p2 );
    sensitive << ( tmp_7_fu_231_p2 );
    sensitive << ( tmp_8_fu_237_p2 );
    sensitive << ( tmp_9_fu_243_p2 );
    sensitive << ( tmp_5_fu_213_p2 );

    SC_METHOD(thread_ap_NS_fsm1);
    sensitive << ( ap_sig_cseq_ST_st1_fsm0_0 );
    sensitive << ( ap_CS_fsm1 );
    sensitive << ( ap_sig_45 );

    SC_METHOD(thread_ap_NS_fsm0);
    sensitive << ( ap_CS_fsm0 );
    sensitive << ( ap_sig_45 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm0 = "1";
    ap_CS_fsm1 = "01";
    CNT_STATE = "0";
    byte_cnt = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "frameSIPO_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, inData_TVALID, "(port)inData_TVALID");
    sc_trace(mVcdFile, inData_TDATA, "(port)inData_TDATA");
    sc_trace(mVcdFile, inData_TREADY, "(port)inData_TREADY");
    sc_trace(mVcdFile, inData_TUSER, "(port)inData_TUSER");
    sc_trace(mVcdFile, header, "(port)header");
    sc_trace(mVcdFile, header_ap_vld, "(port)header_ap_vld");
    sc_trace(mVcdFile, livewire, "(port)livewire");
    sc_trace(mVcdFile, livewire_ap_vld, "(port)livewire_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_CS_fsm0, "ap_CS_fsm0");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm0_0, "ap_sig_cseq_ST_st1_fsm0_0");
    sc_trace(mVcdFile, ap_sig_21, "ap_sig_21");
    sc_trace(mVcdFile, ap_CS_fsm1, "ap_CS_fsm1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st0_fsm1_0, "ap_sig_cseq_ST_st0_fsm1_0");
    sc_trace(mVcdFile, ap_sig_32, "ap_sig_32");
    sc_trace(mVcdFile, tmp_nbreadreq_fu_88_p4, "tmp_nbreadreq_fu_88_p4");
    sc_trace(mVcdFile, ap_sig_45, "ap_sig_45");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm1_1, "ap_sig_cseq_ST_st2_fsm1_1");
    sc_trace(mVcdFile, ap_sig_51, "ap_sig_51");
    sc_trace(mVcdFile, CNT_STATE, "CNT_STATE");
    sc_trace(mVcdFile, byte_cnt, "byte_cnt");
    sc_trace(mVcdFile, inData_TDATA_blk_n, "inData_TDATA_blk_n");
    sc_trace(mVcdFile, tmp_reg_324, "tmp_reg_324");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_reg_324_pp0_iter0, "ap_reg_ppstg_tmp_reg_324_pp0_iter0");
    sc_trace(mVcdFile, CNT_STATE_load_load_fu_183_p1, "CNT_STATE_load_load_fu_183_p1");
    sc_trace(mVcdFile, CNT_STATE_load_reg_328, "CNT_STATE_load_reg_328");
    sc_trace(mVcdFile, ap_reg_ppstg_CNT_STATE_load_reg_328_pp0_iter0, "ap_reg_ppstg_CNT_STATE_load_reg_328_pp0_iter0");
    sc_trace(mVcdFile, tmp_6_fu_225_p2, "tmp_6_fu_225_p2");
    sc_trace(mVcdFile, tmp_6_reg_335, "tmp_6_reg_335");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_6_reg_335_pp0_iter0, "ap_reg_ppstg_tmp_6_reg_335_pp0_iter0");
    sc_trace(mVcdFile, tmp_7_fu_231_p2, "tmp_7_fu_231_p2");
    sc_trace(mVcdFile, tmp_7_reg_339, "tmp_7_reg_339");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_7_reg_339_pp0_iter0, "ap_reg_ppstg_tmp_7_reg_339_pp0_iter0");
    sc_trace(mVcdFile, tmp_8_fu_237_p2, "tmp_8_fu_237_p2");
    sc_trace(mVcdFile, tmp_8_reg_343, "tmp_8_reg_343");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_8_reg_343_pp0_iter0, "ap_reg_ppstg_tmp_8_reg_343_pp0_iter0");
    sc_trace(mVcdFile, tmp_9_fu_243_p2, "tmp_9_fu_243_p2");
    sc_trace(mVcdFile, tmp_9_reg_347, "tmp_9_reg_347");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_9_reg_347_pp0_iter0, "ap_reg_ppstg_tmp_9_reg_347_pp0_iter0");
    sc_trace(mVcdFile, tmp_s_fu_249_p2, "tmp_s_fu_249_p2");
    sc_trace(mVcdFile, tmp_s_reg_351, "tmp_s_reg_351");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_351_pp0_iter0, "ap_reg_ppstg_tmp_s_reg_351_pp0_iter0");
    sc_trace(mVcdFile, icmp_fu_271_p2, "icmp_fu_271_p2");
    sc_trace(mVcdFile, icmp_reg_355, "icmp_reg_355");
    sc_trace(mVcdFile, tmp_1_fu_293_p2, "tmp_1_fu_293_p2");
    sc_trace(mVcdFile, tmp_1_reg_360, "tmp_1_reg_360");
    sc_trace(mVcdFile, ap_reg_phiprechg_storemerge_reg_122pp0_it0, "ap_reg_phiprechg_storemerge_reg_122pp0_it0");
    sc_trace(mVcdFile, tmp_3_fu_195_p2, "tmp_3_fu_195_p2");
    sc_trace(mVcdFile, storemerge_phi_fu_125_p4, "storemerge_phi_fu_125_p4");
    sc_trace(mVcdFile, ap_reg_phiprechg_header_new_reg_133pp0_it0, "ap_reg_phiprechg_header_new_reg_133pp0_it0");
    sc_trace(mVcdFile, ap_reg_phiprechg_header_new_reg_133pp0_it1, "ap_reg_phiprechg_header_new_reg_133pp0_it1");
    sc_trace(mVcdFile, ap_reg_phiprechg_header_new_6_reg_146pp0_it1, "ap_reg_phiprechg_header_new_6_reg_146pp0_it1");
    sc_trace(mVcdFile, header_new_6_phi_fu_154_p14, "header_new_6_phi_fu_154_p14");
    sc_trace(mVcdFile, ap_reg_phiprechg_header_new_6_reg_146pp0_it0, "ap_reg_phiprechg_header_new_6_reg_146pp0_it0");
    sc_trace(mVcdFile, storemerge2_cast_fu_319_p1, "storemerge2_cast_fu_319_p1");
    sc_trace(mVcdFile, tmp_5_fu_213_p2, "tmp_5_fu_213_p2");
    sc_trace(mVcdFile, p_off_fu_255_p2, "p_off_fu_255_p2");
    sc_trace(mVcdFile, tmp_2_fu_261_p4, "tmp_2_fu_261_p4");
    sc_trace(mVcdFile, tmp_4_fu_277_p4, "tmp_4_fu_277_p4");
    sc_trace(mVcdFile, icmp5_fu_287_p2, "icmp5_fu_287_p2");
    sc_trace(mVcdFile, storemerge1_cast_fu_305_p3, "storemerge1_cast_fu_305_p3");
    sc_trace(mVcdFile, storemerge2_fu_312_p3, "storemerge2_fu_312_p3");
    sc_trace(mVcdFile, ap_NS_fsm0, "ap_NS_fsm0");
    sc_trace(mVcdFile, ap_NS_fsm1, "ap_NS_fsm1");
    sc_trace(mVcdFile, ap_sig_160, "ap_sig_160");
    sc_trace(mVcdFile, ap_sig_164, "ap_sig_164");
    sc_trace(mVcdFile, ap_sig_173, "ap_sig_173");
    sc_trace(mVcdFile, ap_sig_191, "ap_sig_191");
    sc_trace(mVcdFile, ap_sig_195, "ap_sig_195");
    sc_trace(mVcdFile, ap_sig_55, "ap_sig_55");
    sc_trace(mVcdFile, ap_sig_136, "ap_sig_136");
    sc_trace(mVcdFile, ap_sig_142, "ap_sig_142");
    sc_trace(mVcdFile, ap_sig_315, "ap_sig_315");
    sc_trace(mVcdFile, ap_sig_82, "ap_sig_82");
    sc_trace(mVcdFile, ap_sig_322, "ap_sig_322");
    sc_trace(mVcdFile, ap_sig_212, "ap_sig_212");
    sc_trace(mVcdFile, ap_sig_325, "ap_sig_325");
#endif

    }
    mHdltvinHandle.open("frameSIPO.hdltvin.dat");
    mHdltvoutHandle.open("frameSIPO.hdltvout.dat");
}

frameSIPO::~frameSIPO() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void frameSIPO::thread_ap_clk_no_reset_() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && 
          !esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && 
          !ap_sig_45.read() && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_225_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_231_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && 
          !esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && 
          !ap_sig_45.read() && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_225_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_231_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_237_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_fu_243_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && 
          !esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && 
          !ap_sig_45.read() && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_225_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_231_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_237_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && 
          !esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && 
          !ap_sig_45.read() && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_225_p2.read())))) {
        CNT_STATE = ap_const_lv1_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && 
                !esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && 
                !ap_sig_45.read() && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_225_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_231_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_237_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_fu_243_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_s_fu_249_p2.read()))) {
        CNT_STATE = tmp_1_fu_293_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && 
                !esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && 
                !ap_sig_45.read() && 
                esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()))) {
        CNT_STATE = storemerge_phi_fu_125_p4.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm0 = ap_ST_st1_fsm0_0;
    } else {
        ap_CS_fsm0 = ap_NS_fsm0.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm1 = ap_ST_st0_fsm1_0;
    } else {
        ap_CS_fsm1 = ap_NS_fsm1.read();
    }
    if (ap_sig_55.read()) {
        if (ap_sig_195.read()) {
            ap_reg_phiprechg_header_new_6_reg_146pp0_it1 = ap_const_lv8_40;
        } else if (ap_sig_191.read()) {
            ap_reg_phiprechg_header_new_6_reg_146pp0_it1 = ap_const_lv8_10;
        } else if (ap_sig_173.read()) {
            ap_reg_phiprechg_header_new_6_reg_146pp0_it1 = ap_const_lv8_4;
        } else if (ap_sig_164.read()) {
            ap_reg_phiprechg_header_new_6_reg_146pp0_it1 = ap_const_lv8_8;
        } else if (ap_sig_160.read()) {
            ap_reg_phiprechg_header_new_6_reg_146pp0_it1 = ap_const_lv8_20;
        } else if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_phiprechg_header_new_6_reg_146pp0_it1 = ap_reg_phiprechg_header_new_6_reg_146pp0_it0.read();
        }
    }
    if (ap_sig_55.read()) {
        if (ap_sig_142.read()) {
            ap_reg_phiprechg_header_new_reg_133pp0_it1 = ap_const_lv8_80;
        } else if (ap_sig_136.read()) {
            ap_reg_phiprechg_header_new_reg_133pp0_it1 = ap_const_lv8_0;
        } else if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_phiprechg_header_new_reg_133pp0_it1 = ap_reg_phiprechg_header_new_reg_133pp0_it0.read();
        }
    }
    if (ap_sig_82.read()) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read())) {
            byte_cnt = tmp_5_fu_213_p2.read();
        } else if (ap_sig_315.read()) {
            byte_cnt = ap_const_lv32_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && !esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && !ap_sig_45.read())) {
        CNT_STATE_load_reg_328 = CNT_STATE.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && !esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && !ap_sig_45.read() && !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_225_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_231_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_237_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_fu_243_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_s_fu_249_p2.read()))) {
        icmp_reg_355 = icmp_fu_271_p2.read();
        tmp_1_reg_360 = tmp_1_fu_293_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && !esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && !ap_sig_45.read() && !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()))) {
        tmp_6_reg_335 = tmp_6_fu_225_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && !esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && !ap_sig_45.read() && !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_225_p2.read()))) {
        tmp_7_reg_339 = tmp_7_fu_231_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && !esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && !ap_sig_45.read() && !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_225_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_231_p2.read()))) {
        tmp_8_reg_343 = tmp_8_fu_237_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && !esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && !ap_sig_45.read() && !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_225_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_231_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_237_p2.read()))) {
        tmp_9_reg_347 = tmp_9_fu_243_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && !ap_sig_45.read())) {
        tmp_reg_324 = tmp_nbreadreq_fu_88_p4.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && !esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && !ap_sig_45.read() && !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_225_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_231_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_237_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_fu_243_p2.read()))) {
        tmp_s_reg_351 = tmp_s_fu_249_p2.read();
    }
}

void frameSIPO::thread_CNT_STATE_load_load_fu_183_p1() {
    CNT_STATE_load_load_fu_183_p1 = CNT_STATE.read();
}

void frameSIPO::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm1_1.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void frameSIPO::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st0_fsm1_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void frameSIPO::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && 
         !ap_sig_45.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void frameSIPO::thread_ap_reg_phiprechg_header_new_6_reg_146pp0_it0() {
    ap_reg_phiprechg_header_new_6_reg_146pp0_it0 =  (sc_lv<8>) ("XXXXXXXX");
}

void frameSIPO::thread_ap_reg_phiprechg_header_new_reg_133pp0_it0() {
    ap_reg_phiprechg_header_new_reg_133pp0_it0 =  (sc_lv<8>) ("XXXXXXXX");
}

void frameSIPO::thread_ap_reg_phiprechg_storemerge_reg_122pp0_it0() {
    ap_reg_phiprechg_storemerge_reg_122pp0_it0 = "X";
}

void frameSIPO::thread_ap_reg_ppstg_CNT_STATE_load_reg_328_pp0_iter0() {
    ap_reg_ppstg_CNT_STATE_load_reg_328_pp0_iter0 = CNT_STATE_load_reg_328.read();
}

void frameSIPO::thread_ap_reg_ppstg_tmp_6_reg_335_pp0_iter0() {
    ap_reg_ppstg_tmp_6_reg_335_pp0_iter0 = tmp_6_reg_335.read();
}

void frameSIPO::thread_ap_reg_ppstg_tmp_7_reg_339_pp0_iter0() {
    ap_reg_ppstg_tmp_7_reg_339_pp0_iter0 = tmp_7_reg_339.read();
}

void frameSIPO::thread_ap_reg_ppstg_tmp_8_reg_343_pp0_iter0() {
    ap_reg_ppstg_tmp_8_reg_343_pp0_iter0 = tmp_8_reg_343.read();
}

void frameSIPO::thread_ap_reg_ppstg_tmp_9_reg_347_pp0_iter0() {
    ap_reg_ppstg_tmp_9_reg_347_pp0_iter0 = tmp_9_reg_347.read();
}

void frameSIPO::thread_ap_reg_ppstg_tmp_reg_324_pp0_iter0() {
    ap_reg_ppstg_tmp_reg_324_pp0_iter0 = tmp_reg_324.read();
}

void frameSIPO::thread_ap_reg_ppstg_tmp_s_reg_351_pp0_iter0() {
    ap_reg_ppstg_tmp_s_reg_351_pp0_iter0 = tmp_s_reg_351.read();
}

void frameSIPO::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void frameSIPO::thread_ap_sig_136() {
    ap_sig_136 = (!esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_195_p2.read()));
}

void frameSIPO::thread_ap_sig_142() {
    ap_sig_142 = (!esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_195_p2.read()));
}

void frameSIPO::thread_ap_sig_160() {
    ap_sig_160 = (!esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_225_p2.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_231_p2.read()));
}

void frameSIPO::thread_ap_sig_164() {
    ap_sig_164 = (!esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_225_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_231_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_237_p2.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_fu_243_p2.read()));
}

void frameSIPO::thread_ap_sig_173() {
    ap_sig_173 = (!esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_225_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_231_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_237_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_fu_243_p2.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_s_fu_249_p2.read()));
}

void frameSIPO::thread_ap_sig_191() {
    ap_sig_191 = (!esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_225_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_231_p2.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_237_p2.read()));
}

void frameSIPO::thread_ap_sig_195() {
    ap_sig_195 = (!esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_225_p2.read()));
}

void frameSIPO::thread_ap_sig_21() {
    ap_sig_21 = esl_seteq<1,1,1>(ap_CS_fsm0.read().range(0, 0), ap_const_lv1_1);
}

void frameSIPO::thread_ap_sig_212() {
    ap_sig_212 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm1_1.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_reg_324_pp0_iter0.read()));
}

void frameSIPO::thread_ap_sig_315() {
    ap_sig_315 = (esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_195_p2.read()));
}

void frameSIPO::thread_ap_sig_32() {
    ap_sig_32 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm1.read().range(0, 0));
}

void frameSIPO::thread_ap_sig_322() {
    ap_sig_322 = (!esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_CNT_STATE_load_reg_328_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_6_reg_335_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_7_reg_339_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_8_reg_343_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_9_reg_347_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_s_reg_351_pp0_iter0.read()));
}

void frameSIPO::thread_ap_sig_325() {
    ap_sig_325 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && !esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, CNT_STATE_load_load_fu_183_p1.read()));
}

void frameSIPO::thread_ap_sig_45() {
    ap_sig_45 = ((esl_seteq<1,1,1>(inData_TVALID.read(), ap_const_logic_0) && 
  !esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0)) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0));
}

void frameSIPO::thread_ap_sig_51() {
    ap_sig_51 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm1.read().range(1, 1));
}

void frameSIPO::thread_ap_sig_55() {
    ap_sig_55 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && !ap_sig_45.read());
}

void frameSIPO::thread_ap_sig_82() {
    ap_sig_82 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && !esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && !ap_sig_45.read());
}

void frameSIPO::thread_ap_sig_cseq_ST_st0_fsm1_0() {
    if (ap_sig_32.read()) {
        ap_sig_cseq_ST_st0_fsm1_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st0_fsm1_0 = ap_const_logic_0;
    }
}

void frameSIPO::thread_ap_sig_cseq_ST_st1_fsm0_0() {
    if (ap_sig_21.read()) {
        ap_sig_cseq_ST_st1_fsm0_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm0_0 = ap_const_logic_0;
    }
}

void frameSIPO::thread_ap_sig_cseq_ST_st2_fsm1_1() {
    if (ap_sig_51.read()) {
        ap_sig_cseq_ST_st2_fsm1_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm1_1 = ap_const_logic_0;
    }
}

void frameSIPO::thread_header() {
    header = header_new_6_phi_fu_154_p14.read();
}

void frameSIPO::thread_header_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm1_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_reg_324_pp0_iter0.read()))) {
        header_ap_vld = ap_const_logic_1;
    } else {
        header_ap_vld = ap_const_logic_0;
    }
}

void frameSIPO::thread_header_new_6_phi_fu_154_p14() {
    if (ap_sig_212.read()) {
        if (ap_sig_322.read()) {
            header_new_6_phi_fu_154_p14 = storemerge2_cast_fu_319_p1.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_CNT_STATE_load_reg_328_pp0_iter0.read())) {
            header_new_6_phi_fu_154_p14 = ap_reg_phiprechg_header_new_reg_133pp0_it1.read();
        } else {
            header_new_6_phi_fu_154_p14 = ap_reg_phiprechg_header_new_6_reg_146pp0_it1.read();
        }
    } else {
        header_new_6_phi_fu_154_p14 = ap_reg_phiprechg_header_new_6_reg_146pp0_it1.read();
    }
}

void frameSIPO::thread_icmp5_fu_287_p2() {
    icmp5_fu_287_p2 = (!tmp_4_fu_277_p4.read().is_01() || !ap_const_lv26_1.is_01())? sc_lv<1>(): (sc_bigint<26>(tmp_4_fu_277_p4.read()) < sc_bigint<26>(ap_const_lv26_1));
}

void frameSIPO::thread_icmp_fu_271_p2() {
    icmp_fu_271_p2 = (!tmp_2_fu_261_p4.read().is_01() || !ap_const_lv31_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_2_fu_261_p4.read() == ap_const_lv31_0);
}

void frameSIPO::thread_inData_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && 
         !esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()))) {
        inData_TDATA_blk_n = inData_TVALID.read();
    } else {
        inData_TDATA_blk_n = ap_const_logic_1;
    }
}

void frameSIPO::thread_inData_TREADY() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && 
          !esl_seteq<1,1,1>(tmp_nbreadreq_fu_88_p4.read(), ap_const_lv1_0) && 
          !ap_sig_45.read()))) {
        inData_TREADY = ap_const_logic_1;
    } else {
        inData_TREADY = ap_const_logic_0;
    }
}

void frameSIPO::thread_livewire() {
    if (ap_sig_212.read()) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_CNT_STATE_load_reg_328_pp0_iter0.read())) {
            livewire = ap_const_lv1_1;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_CNT_STATE_load_reg_328_pp0_iter0.read())) {
            livewire = ap_const_lv1_0;
        } else {
            livewire = "X";
        }
    } else {
        livewire = "X";
    }
}

void frameSIPO::thread_livewire_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm1_1.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_reg_324_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_CNT_STATE_load_reg_328_pp0_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm1_1.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_reg_324_pp0_iter0.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_CNT_STATE_load_reg_328_pp0_iter0.read())))) {
        livewire_ap_vld = ap_const_logic_1;
    } else {
        livewire_ap_vld = ap_const_logic_0;
    }
}

void frameSIPO::thread_p_off_fu_255_p2() {
    p_off_fu_255_p2 = (!byte_cnt.read().is_01() || !ap_const_lv32_FFFFFFF0.is_01())? sc_lv<32>(): (sc_biguint<32>(byte_cnt.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFF0));
}

void frameSIPO::thread_storemerge1_cast_fu_305_p3() {
    storemerge1_cast_fu_305_p3 = (!icmp_reg_355.read()[0].is_01())? sc_lv<3>(): ((icmp_reg_355.read()[0].to_bool())? ap_const_lv3_7: ap_const_lv3_2);
}

void frameSIPO::thread_storemerge2_cast_fu_319_p1() {
    storemerge2_cast_fu_319_p1 = esl_sext<8,3>(storemerge2_fu_312_p3.read());
}

void frameSIPO::thread_storemerge2_fu_312_p3() {
    storemerge2_fu_312_p3 = (!tmp_1_reg_360.read()[0].is_01())? sc_lv<3>(): ((tmp_1_reg_360.read()[0].to_bool())? storemerge1_cast_fu_305_p3.read(): ap_const_lv3_1);
}

void frameSIPO::thread_storemerge_phi_fu_125_p4() {
    if (ap_sig_325.read()) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_195_p2.read())) {
            storemerge_phi_fu_125_p4 = ap_const_lv1_1;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_195_p2.read())) {
            storemerge_phi_fu_125_p4 = ap_const_lv1_0;
        } else {
            storemerge_phi_fu_125_p4 = ap_reg_phiprechg_storemerge_reg_122pp0_it0.read();
        }
    } else {
        storemerge_phi_fu_125_p4 = ap_reg_phiprechg_storemerge_reg_122pp0_it0.read();
    }
}

void frameSIPO::thread_tmp_1_fu_293_p2() {
    tmp_1_fu_293_p2 = (icmp_fu_271_p2.read() | icmp5_fu_287_p2.read());
}

void frameSIPO::thread_tmp_2_fu_261_p4() {
    tmp_2_fu_261_p4 = p_off_fu_255_p2.read().range(31, 1);
}

void frameSIPO::thread_tmp_3_fu_195_p2() {
    tmp_3_fu_195_p2 = (!inData_TDATA.read().is_01() || !ap_const_lv8_D5.is_01())? sc_lv<1>(): sc_lv<1>(inData_TDATA.read() == ap_const_lv8_D5);
}

void frameSIPO::thread_tmp_4_fu_277_p4() {
    tmp_4_fu_277_p4 = tmp_5_fu_213_p2.read().range(31, 6);
}

void frameSIPO::thread_tmp_5_fu_213_p2() {
    tmp_5_fu_213_p2 = (!byte_cnt.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(byte_cnt.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void frameSIPO::thread_tmp_6_fu_225_p2() {
    tmp_6_fu_225_p2 = (!tmp_5_fu_213_p2.read().is_01() || !ap_const_lv32_7.is_01())? sc_lv<1>(): (sc_bigint<32>(tmp_5_fu_213_p2.read()) < sc_bigint<32>(ap_const_lv32_7));
}

void frameSIPO::thread_tmp_7_fu_231_p2() {
    tmp_7_fu_231_p2 = (!tmp_5_fu_213_p2.read().is_01() || !ap_const_lv32_D.is_01())? sc_lv<1>(): (sc_bigint<32>(tmp_5_fu_213_p2.read()) < sc_bigint<32>(ap_const_lv32_D));
}

void frameSIPO::thread_tmp_8_fu_237_p2() {
    tmp_8_fu_237_p2 = (!tmp_5_fu_213_p2.read().is_01() || !ap_const_lv32_D.is_01())? sc_lv<1>(): sc_lv<1>(tmp_5_fu_213_p2.read() == ap_const_lv32_D);
}

void frameSIPO::thread_tmp_9_fu_243_p2() {
    tmp_9_fu_243_p2 = (!tmp_5_fu_213_p2.read().is_01() || !ap_const_lv32_E.is_01())? sc_lv<1>(): sc_lv<1>(tmp_5_fu_213_p2.read() == ap_const_lv32_E);
}

void frameSIPO::thread_tmp_nbreadreq_fu_88_p4() {
    tmp_nbreadreq_fu_88_p4 =  (sc_lv<1>) ((inData_TVALID.read()));
}

void frameSIPO::thread_tmp_s_fu_249_p2() {
    tmp_s_fu_249_p2 = (!tmp_5_fu_213_p2.read().is_01() || !ap_const_lv32_11.is_01())? sc_lv<1>(): (sc_bigint<32>(tmp_5_fu_213_p2.read()) < sc_bigint<32>(ap_const_lv32_11));
}

void frameSIPO::thread_ap_NS_fsm1() {
    switch (ap_CS_fsm1.read().to_uint64()) {
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && !ap_sig_45.read())) {
                ap_NS_fsm1 = ap_ST_st2_fsm1_1;
            } else if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && 
  ap_sig_45.read()))) {
                ap_NS_fsm1 = ap_ST_st0_fsm1_0;
            } else {
                ap_NS_fsm1 = ap_ST_st2_fsm1_1;
            }
            break;
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm0_0.read()) && !ap_sig_45.read())) {
                ap_NS_fsm1 = ap_ST_st2_fsm1_1;
            } else {
                ap_NS_fsm1 = ap_ST_st0_fsm1_0;
            }
            break;
        default : 
            ap_NS_fsm1 =  (sc_lv<2>) ("XX");
            break;
    }
}

void frameSIPO::thread_ap_NS_fsm0() {
    switch (ap_CS_fsm0.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm0 = ap_ST_st1_fsm0_0;
break;
        default : 
            ap_NS_fsm0 = "X";
            break;
    }
}

void frameSIPO::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inData_TVALID\" :  \"" << inData_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inData_TDATA\" :  \"" << inData_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"inData_TREADY\" :  \"" << inData_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inData_TUSER\" :  \"" << inData_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"header\" :  \"" << header.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"header_ap_vld\" :  \"" << header_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"livewire\" :  \"" << livewire.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"livewire_ap_vld\" :  \"" << livewire_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

