// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _frameSIPO_HH_
#define _frameSIPO_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct frameSIPO : public sc_module {
    // Port declarations 19
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_logic > inData_TVALID;
    sc_in< sc_logic > headerData_V_src_MAC_V_TREADY;
    sc_in< sc_lv<8> > inData_TDATA;
    sc_out< sc_logic > inData_TREADY;
    sc_in< sc_lv<2> > inData_TUSER;
    sc_out< sc_lv<48> > headerData_V_src_MAC_V_TDATA;
    sc_out< sc_logic > headerData_V_src_MAC_V_TVALID;
    sc_out< sc_lv<48> > headerData_V_dest_MAC_V_TDATA;
    sc_out< sc_logic > headerData_V_dest_MAC_V_TVALID;
    sc_in< sc_logic > headerData_V_dest_MAC_V_TREADY;
    sc_out< sc_lv<16> > headerData_V_ethertype_V_TDATA;
    sc_out< sc_logic > headerData_V_ethertype_V_TVALID;
    sc_in< sc_logic > headerData_V_ethertype_V_TREADY;


    // Module declarations
    frameSIPO(sc_module_name name);
    SC_HAS_PROCESS(frameSIPO);

    ~frameSIPO();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<1> > ap_CS_fsm0;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm0_0;
    sc_signal< bool > ap_sig_21;
    sc_signal< sc_lv<2> > ap_CS_fsm1;
    sc_signal< sc_logic > ap_sig_cseq_ST_st0_fsm1_0;
    sc_signal< bool > ap_sig_32;
    sc_signal< sc_lv<1> > tmp_nbreadreq_fu_86_p4;
    sc_signal< bool > ap_sig_45;
    sc_signal< sc_lv<1> > tmp_reg_556;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_reg_556_pp0_iter0;
    sc_signal< sc_lv<1> > CNT_STATE_load_reg_560;
    sc_signal< sc_lv<1> > ap_reg_ppstg_CNT_STATE_load_reg_560_pp0_iter0;
    sc_signal< sc_lv<1> > tmp_6_reg_575;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_6_reg_575_pp0_iter0;
    sc_signal< sc_lv<1> > tmp_9_reg_579;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_9_reg_579_pp0_iter0;
    sc_signal< sc_lv<1> > tmp_2_reg_583;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_2_reg_583_pp0_iter0;
    sc_signal< sc_lv<1> > tmp_4_reg_587;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_4_reg_587_pp0_iter0;
    sc_signal< sc_logic > ap_sig_ioackin_headerData_V_src_MAC_V_TREADY;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm1_1;
    sc_signal< bool > ap_sig_81;
    sc_signal< sc_lv<1> > CNT_STATE;
    sc_signal< sc_lv<32> > byte_cnt;
    sc_signal< sc_lv<48> > curr_header_dest_MAC_V;
    sc_signal< sc_lv<48> > curr_header_src_MAC_V;
    sc_signal< sc_lv<16> > curr_header_ethertype_V;
    sc_signal< sc_logic > inData_TDATA_blk_n;
    sc_signal< sc_logic > headerData_V_src_MAC_V_TDATA_blk_n;
    sc_signal< sc_logic > headerData_V_dest_MAC_V_TDATA_blk_n;
    sc_signal< sc_logic > headerData_V_ethertype_V_TDATA_blk_n;
    sc_signal< sc_lv<1> > CNT_STATE_load_load_fu_143_p1;
    sc_signal< sc_lv<8> > tmp_data_V_reg_564;
    sc_signal< sc_lv<1> > tmp_6_fu_179_p2;
    sc_signal< sc_lv<1> > tmp_9_fu_185_p2;
    sc_signal< sc_lv<1> > tmp_2_fu_191_p2;
    sc_signal< sc_lv<1> > tmp_4_fu_197_p2;
    sc_signal< sc_lv<1> > tmp_29_fu_227_p2;
    sc_signal< sc_lv<1> > tmp_29_reg_591;
    sc_signal< sc_lv<6> > tmp_30_fu_233_p1;
    sc_signal< sc_lv<6> > tmp_30_reg_599;
    sc_signal< sc_lv<6> > tmp_31_fu_237_p1;
    sc_signal< sc_lv<6> > tmp_31_reg_607;
    sc_signal< sc_lv<32> > Hi_assign_fu_247_p2;
    sc_signal< sc_lv<32> > Hi_assign_reg_613;
    sc_signal< sc_lv<32> > Lo_assign_fu_253_p2;
    sc_signal< sc_lv<32> > Lo_assign_reg_618;
    sc_signal< sc_lv<6> > tmp_8_fu_259_p1;
    sc_signal< sc_lv<6> > tmp_8_reg_623;
    sc_signal< sc_lv<6> > tmp_10_fu_263_p1;
    sc_signal< sc_lv<6> > tmp_10_reg_631;
    sc_signal< sc_lv<1> > ap_reg_phiprechg_CNT_STATE_new_4_reg_117pp0_it0;
    sc_signal< sc_lv<1> > tmp_3_fu_155_p2;
    sc_signal< sc_lv<1> > CNT_STATE_new_4_phi_fu_120_p14;
    sc_signal< sc_lv<32> > tmp_5_fu_167_p2;
    sc_signal< sc_lv<48> > p_Result_s_fu_544_p2;
    sc_signal< sc_lv<48> > p_Result_1_fu_423_p2;
    sc_signal< sc_lv<16> > p_Result_4_fu_287_p5;
    sc_signal< sc_lv<16> > p_Result_2_fu_305_p5;
    sc_signal< sc_logic > ap_reg_ioackin_headerData_V_src_MAC_V_TREADY;
    sc_signal< sc_logic > ap_reg_ioackin_headerData_V_dest_MAC_V_TREADY;
    sc_signal< sc_logic > ap_reg_ioackin_headerData_V_ethertype_V_TREADY;
    sc_signal< sc_lv<4> > tmp_28_fu_203_p1;
    sc_signal< sc_lv<7> > tmp_s_fu_207_p3;
    sc_signal< sc_lv<7> > Lo_assign_1_fu_221_p2;
    sc_signal< sc_lv<7> > Hi_assign_1_fu_215_p2;
    sc_signal< sc_lv<32> > tmp_1_fu_241_p2;
    sc_signal< sc_lv<6> > tmp_32_fu_325_p2;
    sc_signal< sc_lv<6> > tmp_33_fu_330_p3;
    sc_signal< sc_lv<6> > tmp_35_fu_340_p3;
    sc_signal< sc_lv<6> > tmp_34_fu_335_p3;
    sc_signal< sc_lv<6> > tmp_36_fu_346_p2;
    sc_signal< sc_lv<48> > loc_V_1_fu_322_p1;
    sc_signal< sc_lv<48> > tmp_37_fu_352_p1;
    sc_signal< sc_lv<48> > tmp_40_fu_364_p2;
    sc_signal< sc_lv<48> > tmp_41_fu_370_p4;
    sc_signal< sc_lv<48> > tmp_38_fu_356_p1;
    sc_signal< sc_lv<48> > tmp_39_fu_360_p1;
    sc_signal< sc_lv<48> > tmp_43_fu_387_p2;
    sc_signal< sc_lv<48> > tmp_44_fu_393_p2;
    sc_signal< sc_lv<48> > p_demorgan_fu_399_p2;
    sc_signal< sc_lv<48> > tmp_45_fu_405_p2;
    sc_signal< sc_lv<48> > tmp_42_fu_380_p3;
    sc_signal< sc_lv<48> > tmp_46_fu_411_p2;
    sc_signal< sc_lv<48> > tmp_47_fu_417_p2;
    sc_signal< sc_lv<1> > tmp_7_fu_438_p2;
    sc_signal< sc_lv<6> > tmp_11_fu_442_p2;
    sc_signal< sc_lv<6> > tmp_12_fu_447_p3;
    sc_signal< sc_lv<6> > tmp_14_fu_459_p3;
    sc_signal< sc_lv<6> > tmp_13_fu_453_p3;
    sc_signal< sc_lv<6> > tmp_15_fu_466_p2;
    sc_signal< sc_lv<48> > loc_V_fu_435_p1;
    sc_signal< sc_lv<48> > tmp_16_fu_472_p1;
    sc_signal< sc_lv<48> > tmp_19_fu_484_p2;
    sc_signal< sc_lv<48> > tmp_20_fu_490_p4;
    sc_signal< sc_lv<48> > tmp_17_fu_476_p1;
    sc_signal< sc_lv<48> > tmp_18_fu_480_p1;
    sc_signal< sc_lv<48> > tmp_22_fu_508_p2;
    sc_signal< sc_lv<48> > tmp_23_fu_514_p2;
    sc_signal< sc_lv<48> > p_demorgan3_fu_520_p2;
    sc_signal< sc_lv<48> > tmp_24_fu_526_p2;
    sc_signal< sc_lv<48> > tmp_21_fu_500_p3;
    sc_signal< sc_lv<48> > tmp_25_fu_532_p2;
    sc_signal< sc_lv<48> > tmp_26_fu_538_p2;
    sc_signal< sc_lv<1> > ap_NS_fsm0;
    sc_signal< sc_lv<2> > ap_NS_fsm1;
    sc_signal< bool > ap_sig_113;
    sc_signal< bool > ap_sig_537;
    sc_signal< bool > ap_sig_120;
    sc_signal< bool > ap_sig_541;
    sc_signal< bool > ap_sig_540;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_st1_fsm0_0;
    static const sc_lv<2> ap_ST_st2_fsm1_1;
    static const sc_lv<2> ap_ST_st0_fsm1_0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<8> ap_const_lv8_D5;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<7> ap_const_lv7_67;
    static const sc_lv<7> ap_const_lv7_60;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_37;
    static const sc_lv<32> ap_const_lv32_30;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<6> ap_const_lv6_2F;
    static const sc_lv<32> ap_const_lv32_2F;
    static const sc_lv<48> ap_const_lv48_FFFFFFFFFFFF;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_CNT_STATE_load_load_fu_143_p1();
    void thread_CNT_STATE_new_4_phi_fu_120_p14();
    void thread_Hi_assign_1_fu_215_p2();
    void thread_Hi_assign_fu_247_p2();
    void thread_Lo_assign_1_fu_221_p2();
    void thread_Lo_assign_fu_253_p2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_reg_phiprechg_CNT_STATE_new_4_reg_117pp0_it0();
    void thread_ap_reg_ppstg_CNT_STATE_load_reg_560_pp0_iter0();
    void thread_ap_reg_ppstg_tmp_2_reg_583_pp0_iter0();
    void thread_ap_reg_ppstg_tmp_4_reg_587_pp0_iter0();
    void thread_ap_reg_ppstg_tmp_6_reg_575_pp0_iter0();
    void thread_ap_reg_ppstg_tmp_9_reg_579_pp0_iter0();
    void thread_ap_reg_ppstg_tmp_reg_556_pp0_iter0();
    void thread_ap_rst_n_inv();
    void thread_ap_sig_113();
    void thread_ap_sig_120();
    void thread_ap_sig_21();
    void thread_ap_sig_32();
    void thread_ap_sig_45();
    void thread_ap_sig_537();
    void thread_ap_sig_540();
    void thread_ap_sig_541();
    void thread_ap_sig_81();
    void thread_ap_sig_cseq_ST_st0_fsm1_0();
    void thread_ap_sig_cseq_ST_st1_fsm0_0();
    void thread_ap_sig_cseq_ST_st2_fsm1_1();
    void thread_ap_sig_ioackin_headerData_V_src_MAC_V_TREADY();
    void thread_headerData_V_dest_MAC_V_TDATA();
    void thread_headerData_V_dest_MAC_V_TDATA_blk_n();
    void thread_headerData_V_dest_MAC_V_TVALID();
    void thread_headerData_V_ethertype_V_TDATA();
    void thread_headerData_V_ethertype_V_TDATA_blk_n();
    void thread_headerData_V_ethertype_V_TVALID();
    void thread_headerData_V_src_MAC_V_TDATA();
    void thread_headerData_V_src_MAC_V_TDATA_blk_n();
    void thread_headerData_V_src_MAC_V_TVALID();
    void thread_inData_TDATA_blk_n();
    void thread_inData_TREADY();
    void thread_loc_V_1_fu_322_p1();
    void thread_loc_V_fu_435_p1();
    void thread_p_Result_1_fu_423_p2();
    void thread_p_Result_2_fu_305_p5();
    void thread_p_Result_4_fu_287_p5();
    void thread_p_Result_s_fu_544_p2();
    void thread_p_demorgan3_fu_520_p2();
    void thread_p_demorgan_fu_399_p2();
    void thread_tmp_10_fu_263_p1();
    void thread_tmp_11_fu_442_p2();
    void thread_tmp_12_fu_447_p3();
    void thread_tmp_13_fu_453_p3();
    void thread_tmp_14_fu_459_p3();
    void thread_tmp_15_fu_466_p2();
    void thread_tmp_16_fu_472_p1();
    void thread_tmp_17_fu_476_p1();
    void thread_tmp_18_fu_480_p1();
    void thread_tmp_19_fu_484_p2();
    void thread_tmp_1_fu_241_p2();
    void thread_tmp_20_fu_490_p4();
    void thread_tmp_21_fu_500_p3();
    void thread_tmp_22_fu_508_p2();
    void thread_tmp_23_fu_514_p2();
    void thread_tmp_24_fu_526_p2();
    void thread_tmp_25_fu_532_p2();
    void thread_tmp_26_fu_538_p2();
    void thread_tmp_28_fu_203_p1();
    void thread_tmp_29_fu_227_p2();
    void thread_tmp_2_fu_191_p2();
    void thread_tmp_30_fu_233_p1();
    void thread_tmp_31_fu_237_p1();
    void thread_tmp_32_fu_325_p2();
    void thread_tmp_33_fu_330_p3();
    void thread_tmp_34_fu_335_p3();
    void thread_tmp_35_fu_340_p3();
    void thread_tmp_36_fu_346_p2();
    void thread_tmp_37_fu_352_p1();
    void thread_tmp_38_fu_356_p1();
    void thread_tmp_39_fu_360_p1();
    void thread_tmp_3_fu_155_p2();
    void thread_tmp_40_fu_364_p2();
    void thread_tmp_41_fu_370_p4();
    void thread_tmp_42_fu_380_p3();
    void thread_tmp_43_fu_387_p2();
    void thread_tmp_44_fu_393_p2();
    void thread_tmp_45_fu_405_p2();
    void thread_tmp_46_fu_411_p2();
    void thread_tmp_47_fu_417_p2();
    void thread_tmp_4_fu_197_p2();
    void thread_tmp_5_fu_167_p2();
    void thread_tmp_6_fu_179_p2();
    void thread_tmp_7_fu_438_p2();
    void thread_tmp_8_fu_259_p1();
    void thread_tmp_9_fu_185_p2();
    void thread_tmp_nbreadreq_fu_86_p4();
    void thread_tmp_s_fu_207_p3();
    void thread_ap_NS_fsm1();
    void thread_ap_NS_fsm0();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
