// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="frameSIPO,hls_ip_2016_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.853000,HLS_SYN_LAT=0,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=34,HLS_SYN_LUT=145}" *)

module frameSIPO (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inData_TDATA,
        inData_TVALID,
        inData_TREADY,
        inData_TUSER,
        outData_TDATA,
        outData_TVALID,
        outData_TREADY,
        outData_TUSER,
        sfd_detected,
        sfd_detected_ap_vld,
        src_addr,
        src_addr_ap_vld,
        dest_addr,
        dest_addr_ap_vld,
        ethertype,
        ethertype_ap_vld,
        ping,
        ping_ap_vld
);

parameter    ap_ST_st1_fsm_0 = 1'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv8_D5 = 8'b11010101;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv16_800 = 16'b100000000000;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] inData_TDATA;
input   inData_TVALID;
output   inData_TREADY;
input  [127:0] inData_TUSER;
input  [7:0] outData_TDATA;
input   outData_TVALID;
output   outData_TREADY;
input  [127:0] outData_TUSER;
output  [0:0] sfd_detected;
output   sfd_detected_ap_vld;
output  [0:0] src_addr;
output   src_addr_ap_vld;
output  [0:0] dest_addr;
output   dest_addr_ap_vld;
output  [0:0] ethertype;
output   ethertype_ap_vld;
output  [0:0] ping;
output   ping_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg inData_TREADY;
reg sfd_detected_ap_vld;
reg[0:0] src_addr;
reg src_addr_ap_vld;
reg[0:0] dest_addr;
reg dest_addr_ap_vld;
reg[0:0] ethertype;
reg ethertype_ap_vld;
reg ping_ap_vld;

reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_18;
reg   [0:0] CNT_STATE;
reg   [31:0] byte_cnt;
reg    inData_TDATA_blk_n;
wire   [0:0] tmp_nbreadreq_fu_70_p4;
reg   [0:0] sfd_detected_flag_1_phi_fu_132_p12;
reg    ap_sig_57;
wire   [0:0] CNT_STATE_load_load_fu_196_p1;
wire   [0:0] tmp_6_fu_239_p2;
wire   [0:0] tmp_7_fu_245_p2;
wire   [0:0] tmp_8_fu_251_p2;
wire   [0:0] tmp_2_fu_257_p2;
reg   [0:0] sfd_detected_new_1_phi_fu_155_p12;
wire   [0:0] tmp_3_fu_214_p2;
reg   [15:0] packet_type_load_1_phi_fu_178_p12;
wire   [15:0] tmp_s_fu_274_p3;
wire   [15:0] tmp_4_fu_269_p1;
wire   [31:0] tmp_5_fu_227_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_sig_192;
reg    ap_sig_127;
reg    ap_sig_51;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'b1;
#0 CNT_STATE = 1'b0;
#0 byte_cnt = 32'b00000000000000000000000000000000;
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_127) begin
        if (ap_sig_192) begin
            CNT_STATE <= 1'b0;
        end else if ((1'b0 == CNT_STATE_load_load_fu_196_p1)) begin
            CNT_STATE <= tmp_3_fu_214_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_127) begin
        if (~(1'b0 == CNT_STATE_load_load_fu_196_p1)) begin
            byte_cnt <= tmp_5_fu_227_p2;
        end else if ((1'b0 == CNT_STATE_load_load_fu_196_p1)) begin
            byte_cnt <= ap_const_lv32_0;
        end
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_57)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_57)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_18) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & ~(1'b0 == tmp_6_fu_239_p2))) begin
        dest_addr = 1'b1;
    end else if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & (1'b0 == tmp_7_fu_245_p2) & (1'b0 == tmp_8_fu_251_p2) & (1'b0 == tmp_2_fu_257_p2)) | ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & (1'b0 == CNT_STATE_load_load_fu_196_p1)))) begin
        dest_addr = 1'b0;
    end else begin
        dest_addr = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & ~(1'b0 == tmp_6_fu_239_p2)) | ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & (1'b0 == tmp_7_fu_245_p2) & (1'b0 == tmp_8_fu_251_p2) & (1'b0 == tmp_2_fu_257_p2)) | ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & (1'b0 == CNT_STATE_load_load_fu_196_p1)))) begin
        dest_addr_ap_vld = 1'b1;
    end else begin
        dest_addr_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & (1'b0 == tmp_7_fu_245_p2) & ~(1'b0 == tmp_8_fu_251_p2)) | ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & (1'b0 == tmp_7_fu_245_p2) & (1'b0 == tmp_8_fu_251_p2) & ~(1'b0 == tmp_2_fu_257_p2)))) begin
        ethertype = 1'b1;
    end else if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & (1'b0 == tmp_7_fu_245_p2) & (1'b0 == tmp_8_fu_251_p2) & (1'b0 == tmp_2_fu_257_p2)) | ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & (1'b0 == CNT_STATE_load_load_fu_196_p1)))) begin
        ethertype = 1'b0;
    end else begin
        ethertype = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & (1'b0 == tmp_7_fu_245_p2) & ~(1'b0 == tmp_8_fu_251_p2)) | ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & (1'b0 == tmp_7_fu_245_p2) & (1'b0 == tmp_8_fu_251_p2) & ~(1'b0 == tmp_2_fu_257_p2)) | ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & (1'b0 == tmp_7_fu_245_p2) & (1'b0 == tmp_8_fu_251_p2) & (1'b0 == tmp_2_fu_257_p2)) | ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & (1'b0 == CNT_STATE_load_load_fu_196_p1)))) begin
        ethertype_ap_vld = 1'b1;
    end else begin
        ethertype_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4))) begin
        inData_TDATA_blk_n = inData_TVALID;
    end else begin
        inData_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57)) begin
        inData_TREADY = 1'b1;
    end else begin
        inData_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & (1'b0 == tmp_7_fu_245_p2) & (1'b0 == tmp_8_fu_251_p2) & ~(1'b0 == tmp_2_fu_257_p2))) begin
        packet_type_load_1_phi_fu_178_p12 = tmp_4_fu_269_p1;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & (1'b0 == tmp_7_fu_245_p2) & ~(1'b0 == tmp_8_fu_251_p2))) begin
        packet_type_load_1_phi_fu_178_p12 = tmp_s_fu_274_p3;
    end else if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & ~(1'b0 == tmp_6_fu_239_p2)) | ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & ~(1'b0 == tmp_7_fu_245_p2)) | ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & (1'b0 == tmp_7_fu_245_p2) & (1'b0 == tmp_8_fu_251_p2) & (1'b0 == tmp_2_fu_257_p2)) | ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & (1'b0 == CNT_STATE_load_load_fu_196_p1)))) begin
        packet_type_load_1_phi_fu_178_p12 = ap_const_lv16_0;
    end else begin
        packet_type_load_1_phi_fu_178_p12 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57)) begin
        ping_ap_vld = 1'b1;
    end else begin
        ping_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & ~(1'b0 == sfd_detected_flag_1_phi_fu_132_p12))) begin
        sfd_detected_ap_vld = 1'b1;
    end else begin
        sfd_detected_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & (1'b0 == tmp_7_fu_245_p2) & (1'b0 == tmp_8_fu_251_p2) & (1'b0 == tmp_2_fu_257_p2)) | ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & (1'b0 == CNT_STATE_load_load_fu_196_p1)))) begin
        sfd_detected_flag_1_phi_fu_132_p12 = 1'b1;
    end else if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & ~(1'b0 == tmp_6_fu_239_p2)) | ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & ~(1'b0 == tmp_7_fu_245_p2)) | ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & (1'b0 == tmp_7_fu_245_p2) & ~(1'b0 == tmp_8_fu_251_p2)) | ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & (1'b0 == tmp_7_fu_245_p2) & (1'b0 == tmp_8_fu_251_p2) & ~(1'b0 == tmp_2_fu_257_p2)))) begin
        sfd_detected_flag_1_phi_fu_132_p12 = 1'b0;
    end else begin
        sfd_detected_flag_1_phi_fu_132_p12 = 'bx;
    end
end

always @ (*) begin
    if (ap_sig_51) begin
        if ((1'b0 == CNT_STATE_load_load_fu_196_p1)) begin
            sfd_detected_new_1_phi_fu_155_p12 = tmp_3_fu_214_p2;
        end else if (ap_sig_192) begin
            sfd_detected_new_1_phi_fu_155_p12 = 1'b0;
        end else begin
            sfd_detected_new_1_phi_fu_155_p12 = 'bx;
        end
    end else begin
        sfd_detected_new_1_phi_fu_155_p12 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & ~(1'b0 == tmp_7_fu_245_p2))) begin
        src_addr = 1'b1;
    end else if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & (1'b0 == tmp_7_fu_245_p2) & (1'b0 == tmp_8_fu_251_p2) & (1'b0 == tmp_2_fu_257_p2)) | ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & (1'b0 == CNT_STATE_load_load_fu_196_p1)))) begin
        src_addr = 1'b0;
    end else begin
        src_addr = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & ~(1'b0 == tmp_7_fu_245_p2)) | ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & ~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & (1'b0 == tmp_7_fu_245_p2) & (1'b0 == tmp_8_fu_251_p2) & (1'b0 == tmp_2_fu_257_p2)) | ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57 & (1'b0 == CNT_STATE_load_load_fu_196_p1)))) begin
        src_addr_ap_vld = 1'b1;
    end else begin
        src_addr_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign CNT_STATE_load_load_fu_196_p1 = CNT_STATE;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

always @ (*) begin
    ap_sig_127 = ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4) & ~ap_sig_57);
end

always @ (*) begin
    ap_sig_18 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_192 = (~(1'b0 == CNT_STATE_load_load_fu_196_p1) & (1'b0 == tmp_6_fu_239_p2) & (1'b0 == tmp_7_fu_245_p2) & (1'b0 == tmp_8_fu_251_p2) & (1'b0 == tmp_2_fu_257_p2));
end

always @ (*) begin
    ap_sig_51 = ((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(1'b0 == tmp_nbreadreq_fu_70_p4));
end

always @ (*) begin
    ap_sig_57 = ((~(1'b0 == tmp_nbreadreq_fu_70_p4) & (inData_TVALID == 1'b0)) | (ap_start == 1'b0));
end

assign outData_TREADY = 1'b0;

assign ping = ((packet_type_load_1_phi_fu_178_p12 == ap_const_lv16_800) ? 1'b1 : 1'b0);

assign sfd_detected = sfd_detected_new_1_phi_fu_155_p12;

assign tmp_2_fu_257_p2 = ((tmp_5_fu_227_p2 == ap_const_lv32_E) ? 1'b1 : 1'b0);

assign tmp_3_fu_214_p2 = ((inData_TDATA == ap_const_lv8_D5) ? 1'b1 : 1'b0);

assign tmp_4_fu_269_p1 = inData_TDATA;

assign tmp_5_fu_227_p2 = (byte_cnt + ap_const_lv32_1);

assign tmp_6_fu_239_p2 = (($signed(tmp_5_fu_227_p2) < $signed(32'b111)) ? 1'b1 : 1'b0);

assign tmp_7_fu_245_p2 = (($signed(tmp_5_fu_227_p2) < $signed(32'b1101)) ? 1'b1 : 1'b0);

assign tmp_8_fu_251_p2 = ((tmp_5_fu_227_p2 == ap_const_lv32_D) ? 1'b1 : 1'b0);

assign tmp_nbreadreq_fu_70_p4 = inData_TVALID;

assign tmp_s_fu_274_p3 = {{inData_TDATA}, {ap_const_lv8_0}};

endmodule //frameSIPO
